import { MigrationInterface, QueryRunner } from 'typeorm';

/** Stable insertion order for events that share the same millisecond. */
export class CommerceOutboxSequence1793433600000 implements MigrationInterface {
  name = 'CommerceOutboxSequence1793433600000';

  async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      'ALTER TABLE "orders"."commerce_outbox_events" ADD "sequence" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL',
    );
    await queryRunner.query(
      'CREATE UNIQUE INDEX "commerce_outbox_sequence_key" ON "orders"."commerce_outbox_events" ("sequence")',
    );
  }

  async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      'DROP INDEX "orders"."commerce_outbox_sequence_key"',
    );
    await queryRunner.query(
      'ALTER TABLE "orders"."commerce_outbox_events" DROP COLUMN "sequence"',
    );
  }
}
