export interface ReferenceAirport {
  code: string;
  cityFa: string;
  airportNameFa: string;
  countryFa: 'ایران' | 'امارات' | 'عمان' | 'قطر' | 'ترکیه' | 'ارمنستان' | 'عراق';
  tz: string;
}

/**
 * Real airport reference data used only by the commercial manager's catalog
 * picker. An airport becomes visible to customers only after the manager adds
 * it to the active server-side catalog.
 */
export const AIRPORT_REFERENCE_CATALOG: readonly ReferenceAirport[] = [
  { code: 'THR', cityFa: 'تهران', airportNameFa: 'فرودگاه بین‌المللی مهرآباد', countryFa: 'ایران', tz: 'Asia/Tehran' },
  { code: 'IKA', cityFa: 'تهران', airportNameFa: 'فرودگاه بین‌المللی امام خمینی', countryFa: 'ایران', tz: 'Asia/Tehran' },
  { code: 'MHD', cityFa: 'مشهد', airportNameFa: 'فرودگاه بین‌المللی شهید هاشمی‌نژاد', countryFa: 'ایران', tz: 'Asia/Tehran' },
  { code: 'SYZ', cityFa: 'شیراز', airportNameFa: 'فرودگاه بین‌المللی شهید دستغیب', countryFa: 'ایران', tz: 'Asia/Tehran' },
  { code: 'IFN', cityFa: 'اصفهان', airportNameFa: 'فرودگاه بین‌المللی شهید بهشتی', countryFa: 'ایران', tz: 'Asia/Tehran' },
  { code: 'TBZ', cityFa: 'تبریز', airportNameFa: 'فرودگاه بین‌المللی شهید مدنی', countryFa: 'ایران', tz: 'Asia/Tehran' },
  { code: 'KIH', cityFa: 'کیش', airportNameFa: 'فرودگاه بین‌المللی کیش', countryFa: 'ایران', tz: 'Asia/Tehran' },
  { code: 'GSM', cityFa: 'قشم', airportNameFa: 'فرودگاه بین‌المللی قشم', countryFa: 'ایران', tz: 'Asia/Tehran' },
  { code: 'BND', cityFa: 'بندرعباس', airportNameFa: 'فرودگاه بین‌المللی بندرعباس', countryFa: 'ایران', tz: 'Asia/Tehran' },
  { code: 'AWZ', cityFa: 'اهواز', airportNameFa: 'فرودگاه بین‌المللی شهید قاسم سلیمانی', countryFa: 'ایران', tz: 'Asia/Tehran' },
  { code: 'RAS', cityFa: 'رشت', airportNameFa: 'فرودگاه بین‌المللی سردار جنگل', countryFa: 'ایران', tz: 'Asia/Tehran' },
  { code: 'SRY', cityFa: 'ساری', airportNameFa: 'فرودگاه بین‌المللی دشت ناز', countryFa: 'ایران', tz: 'Asia/Tehran' },
  { code: 'GBT', cityFa: 'گرگان', airportNameFa: 'فرودگاه بین‌المللی گرگان', countryFa: 'ایران', tz: 'Asia/Tehran' },
  { code: 'KER', cityFa: 'کرمان', airportNameFa: 'فرودگاه بین‌المللی آیت‌الله هاشمی رفسنجانی', countryFa: 'ایران', tz: 'Asia/Tehran' },
  { code: 'KSH', cityFa: 'کرمانشاه', airportNameFa: 'فرودگاه بین‌المللی شهید اشرفی اصفهانی', countryFa: 'ایران', tz: 'Asia/Tehran' },
  { code: 'OMH', cityFa: 'ارومیه', airportNameFa: 'فرودگاه بین‌المللی شهید باکری', countryFa: 'ایران', tz: 'Asia/Tehran' },
  { code: 'ADU', cityFa: 'اردبیل', airportNameFa: 'فرودگاه بین‌المللی اردبیل', countryFa: 'ایران', tz: 'Asia/Tehran' },
  { code: 'ZAH', cityFa: 'زاهدان', airportNameFa: 'فرودگاه بین‌المللی زاهدان', countryFa: 'ایران', tz: 'Asia/Tehran' },
  { code: 'BUZ', cityFa: 'بوشهر', airportNameFa: 'فرودگاه بین‌المللی بوشهر', countryFa: 'ایران', tz: 'Asia/Tehran' },
  { code: 'AZD', cityFa: 'یزد', airportNameFa: 'فرودگاه بین‌المللی شهید صدوقی', countryFa: 'ایران', tz: 'Asia/Tehran' },
  { code: 'PGU', cityFa: 'عسلویه', airportNameFa: 'فرودگاه بین‌المللی خلیج فارس', countryFa: 'ایران', tz: 'Asia/Tehran' },
  { code: 'ZBR', cityFa: 'چابهار', airportNameFa: 'فرودگاه کنارک', countryFa: 'ایران', tz: 'Asia/Tehran' },
  { code: 'ABD', cityFa: 'آبادان', airportNameFa: 'فرودگاه بین‌المللی آیت‌الله جمی', countryFa: 'ایران', tz: 'Asia/Tehran' },
  { code: 'DEF', cityFa: 'دزفول', airportNameFa: 'فرودگاه دزفول', countryFa: 'ایران', tz: 'Asia/Tehran' },
  { code: 'IIL', cityFa: 'ایلام', airportNameFa: 'فرودگاه شهدای ایلام', countryFa: 'ایران', tz: 'Asia/Tehran' },
  { code: 'KHD', cityFa: 'خرم‌آباد', airportNameFa: 'فرودگاه خرم‌آباد', countryFa: 'ایران', tz: 'Asia/Tehran' },
  { code: 'SDG', cityFa: 'سنندج', airportNameFa: 'فرودگاه سنندج', countryFa: 'ایران', tz: 'Asia/Tehran' },
  { code: 'XBJ', cityFa: 'بیرجند', airportNameFa: 'فرودگاه بین‌المللی شهید کاوه', countryFa: 'ایران', tz: 'Asia/Tehran' },
  { code: 'BJB', cityFa: 'بجنورد', airportNameFa: 'فرودگاه بجنورد', countryFa: 'ایران', tz: 'Asia/Tehran' },
  { code: 'AFZ', cityFa: 'سبزوار', airportNameFa: 'فرودگاه سبزوار', countryFa: 'ایران', tz: 'Asia/Tehran' },
  { code: 'LRR', cityFa: 'لار', airportNameFa: 'فرودگاه بین‌المللی آیت‌الله آیت‌اللهی لارستان', countryFa: 'ایران', tz: 'Asia/Tehran' },
  { code: 'LFM', cityFa: 'لامرد', airportNameFa: 'فرودگاه بین‌المللی لامرد', countryFa: 'ایران', tz: 'Asia/Tehran' },
  { code: 'RZR', cityFa: 'رامسر', airportNameFa: 'فرودگاه رامسر', countryFa: 'ایران', tz: 'Asia/Tehran' },
  { code: 'CQD', cityFa: 'شهرکرد', airportNameFa: 'فرودگاه شهرکرد', countryFa: 'ایران', tz: 'Asia/Tehran' },
  { code: 'JWN', cityFa: 'زنجان', airportNameFa: 'فرودگاه زنجان', countryFa: 'ایران', tz: 'Asia/Tehran' },
  { code: 'HDM', cityFa: 'همدان', airportNameFa: 'فرودگاه همدان', countryFa: 'ایران', tz: 'Asia/Tehran' },
  { code: 'AEU', cityFa: 'ابوموسی', airportNameFa: 'فرودگاه ابوموسی', countryFa: 'ایران', tz: 'Asia/Tehran' },
  { code: 'AKW', cityFa: 'آغاجاری', airportNameFa: 'فرودگاه آغاجاری', countryFa: 'ایران', tz: 'Asia/Tehran' },
  { code: 'AJK', cityFa: 'اراک', airportNameFa: 'فرودگاه بین‌المللی اراک', countryFa: 'ایران', tz: 'Asia/Tehran' },
  { code: 'IAQ', cityFa: 'بهرگان', airportNameFa: 'فرودگاه بهرگان', countryFa: 'ایران', tz: 'Asia/Tehran' },
  { code: 'BXR', cityFa: 'بم', airportNameFa: 'فرودگاه بم', countryFa: 'ایران', tz: 'Asia/Tehran' },
  { code: 'HDR', cityFa: 'بندرعباس', airportNameFa: 'فرودگاه هوادریا', countryFa: 'ایران', tz: 'Asia/Tehran' },
  { code: 'BDH', cityFa: 'بندرلنگه', airportNameFa: 'فرودگاه بندرلنگه', countryFa: 'ایران', tz: 'Asia/Tehran' },
  { code: 'GCH', cityFa: 'گچساران', airportNameFa: 'فرودگاه گچساران', countryFa: 'ایران', tz: 'Asia/Tehran' },
  { code: 'FAZ', cityFa: 'فسا', airportNameFa: 'فرودگاه فسا', countryFa: 'ایران', tz: 'Asia/Tehran' },
  { code: 'IHR', cityFa: 'ایرانشهر', airportNameFa: 'فرودگاه ایرانشهر', countryFa: 'ایران', tz: 'Asia/Tehran' },
  { code: 'JAR', cityFa: 'جهرم', airportNameFa: 'فرودگاه بین‌المللی جهرم', countryFa: 'ایران', tz: 'Asia/Tehran' },
  { code: 'JSK', cityFa: 'جاسک', airportNameFa: 'فرودگاه جاسک', countryFa: 'ایران', tz: 'Asia/Tehran' },
  { code: 'JYR', cityFa: 'جیرفت', airportNameFa: 'فرودگاه جیرفت', countryFa: 'ایران', tz: 'Asia/Tehran' },
  { code: 'KLM', cityFa: 'کلاله', airportNameFa: 'فرودگاه کلاله', countryFa: 'ایران', tz: 'Asia/Tehran' },
  { code: 'KNR', cityFa: 'کنگان', airportNameFa: 'فرودگاه جم', countryFa: 'ایران', tz: 'Asia/Tehran' },
  { code: 'PYK', cityFa: 'کرج', airportNameFa: 'فرودگاه پیام', countryFa: 'ایران', tz: 'Asia/Tehran' },
  { code: 'KKS', cityFa: 'کاشان', airportNameFa: 'فرودگاه کاشان', countryFa: 'ایران', tz: 'Asia/Tehran' },
  { code: 'KHA', cityFa: 'پیرانشهر', airportNameFa: 'فرودگاه خانه', countryFa: 'ایران', tz: 'Asia/Tehran' },
  { code: 'KHK', cityFa: 'جزیره خارک', airportNameFa: 'فرودگاه خارک', countryFa: 'ایران', tz: 'Asia/Tehran' },
  { code: 'KHY', cityFa: 'خوی', airportNameFa: 'فرودگاه خوی', countryFa: 'ایران', tz: 'Asia/Tehran' },
  { code: 'LVP', cityFa: 'جزیره لاوان', airportNameFa: 'فرودگاه لاوان', countryFa: 'ایران', tz: 'Asia/Tehran' },
  { code: 'MRX', cityFa: 'ماهشهر', airportNameFa: 'فرودگاه ماهشهر', countryFa: 'ایران', tz: 'Asia/Tehran' },
  { code: 'IMQ', cityFa: 'ماکو', airportNameFa: 'فرودگاه بین‌المللی ماکو', countryFa: 'ایران', tz: 'Asia/Tehran' },
  { code: 'ACP', cityFa: 'مراغه', airportNameFa: 'فرودگاه سهند', countryFa: 'ایران', tz: 'Asia/Tehran' },
  { code: 'NSH', cityFa: 'نوشهر', airportNameFa: 'فرودگاه نوشهر', countryFa: 'ایران', tz: 'Asia/Tehran' },
  { code: 'PFQ', cityFa: 'پارس‌آباد', airportNameFa: 'فرودگاه پارس‌آباد مغان', countryFa: 'ایران', tz: 'Asia/Tehran' },
  { code: 'GZW', cityFa: 'قزوین', airportNameFa: 'فرودگاه قزوین', countryFa: 'ایران', tz: 'Asia/Tehran' },
  { code: 'RJN', cityFa: 'رفسنجان', airportNameFa: 'فرودگاه رفسنجان', countryFa: 'ایران', tz: 'Asia/Tehran' },
  { code: 'TQZ', cityFa: 'سقز', airportNameFa: 'فرودگاه سقز', countryFa: 'ایران', tz: 'Asia/Tehran' },
  { code: 'CKT', cityFa: 'سرخس', airportNameFa: 'فرودگاه سرخس', countryFa: 'ایران', tz: 'Asia/Tehran' },
  { code: 'SNX', cityFa: 'سمنان', airportNameFa: 'فرودگاه سمنان', countryFa: 'ایران', tz: 'Asia/Tehran' },
  { code: 'RUD', cityFa: 'شاهرود', airportNameFa: 'فرودگاه شاهرود', countryFa: 'ایران', tz: 'Asia/Tehran' },
  { code: 'SYJ', cityFa: 'سیرجان', airportNameFa: 'فرودگاه سیرجان', countryFa: 'ایران', tz: 'Asia/Tehran' },
  { code: 'SXI', cityFa: 'جزیره سیری', airportNameFa: 'فرودگاه سیری', countryFa: 'ایران', tz: 'Asia/Tehran' },
  { code: 'TCX', cityFa: 'طبس', airportNameFa: 'فرودگاه طبس', countryFa: 'ایران', tz: 'Asia/Tehran' },
  { code: 'YES', cityFa: 'یاسوج', airportNameFa: 'فرودگاه یاسوج', countryFa: 'ایران', tz: 'Asia/Tehran' },
  { code: 'ACZ', cityFa: 'زابل', airportNameFa: 'فرودگاه زابل', countryFa: 'ایران', tz: 'Asia/Tehran' },

  { code: 'DXB', cityFa: 'دبی', airportNameFa: 'فرودگاه بین‌المللی دبی', countryFa: 'امارات', tz: 'Asia/Dubai' },
  { code: 'DWC', cityFa: 'دبی', airportNameFa: 'فرودگاه بین‌المللی آل مکتوم', countryFa: 'امارات', tz: 'Asia/Dubai' },
  { code: 'AUH', cityFa: 'ابوظبی', airportNameFa: 'فرودگاه بین‌المللی زاید', countryFa: 'امارات', tz: 'Asia/Dubai' },
  { code: 'SHJ', cityFa: 'شارجه', airportNameFa: 'فرودگاه بین‌المللی شارجه', countryFa: 'امارات', tz: 'Asia/Dubai' },
  { code: 'RKT', cityFa: 'رأس‌الخیمه', airportNameFa: 'فرودگاه بین‌المللی رأس‌الخیمه', countryFa: 'امارات', tz: 'Asia/Dubai' },
  { code: 'AAN', cityFa: 'العین', airportNameFa: 'فرودگاه بین‌المللی العین', countryFa: 'امارات', tz: 'Asia/Dubai' },
  { code: 'FJR', cityFa: 'فجیره', airportNameFa: 'فرودگاه بین‌المللی فجیره', countryFa: 'امارات', tz: 'Asia/Dubai' },

  { code: 'MCT', cityFa: 'مسقط', airportNameFa: 'فرودگاه بین‌المللی مسقط', countryFa: 'عمان', tz: 'Asia/Muscat' },
  { code: 'SLL', cityFa: 'صلاله', airportNameFa: 'فرودگاه صلاله', countryFa: 'عمان', tz: 'Asia/Muscat' },
  { code: 'OHS', cityFa: 'صحار', airportNameFa: 'فرودگاه صحار', countryFa: 'عمان', tz: 'Asia/Muscat' },
  { code: 'DQM', cityFa: 'دقم', airportNameFa: 'فرودگاه دقم', countryFa: 'عمان', tz: 'Asia/Muscat' },

  { code: 'DOH', cityFa: 'دوحه', airportNameFa: 'فرودگاه بین‌المللی حمد', countryFa: 'قطر', tz: 'Asia/Qatar' },

  { code: 'IST', cityFa: 'استانبول', airportNameFa: 'فرودگاه استانبول', countryFa: 'ترکیه', tz: 'Europe/Istanbul' },
  { code: 'SAW', cityFa: 'استانبول', airportNameFa: 'فرودگاه بین‌المللی صبیحه گوکچن', countryFa: 'ترکیه', tz: 'Europe/Istanbul' },
  { code: 'ESB', cityFa: 'آنکارا', airportNameFa: 'فرودگاه اسن‌بوغا', countryFa: 'ترکیه', tz: 'Europe/Istanbul' },
  { code: 'AYT', cityFa: 'آنتالیا', airportNameFa: 'فرودگاه آنتالیا', countryFa: 'ترکیه', tz: 'Europe/Istanbul' },
  { code: 'VAN', cityFa: 'وان', airportNameFa: 'فرودگاه فرید ملن', countryFa: 'ترکیه', tz: 'Europe/Istanbul' },
  { code: 'ADB', cityFa: 'ازمیر', airportNameFa: 'فرودگاه عدنان مندرس', countryFa: 'ترکیه', tz: 'Europe/Istanbul' },
  { code: 'TZX', cityFa: 'ترابزون', airportNameFa: 'فرودگاه ترابزون', countryFa: 'ترکیه', tz: 'Europe/Istanbul' },

  { code: 'EVN', cityFa: 'ایروان', airportNameFa: 'فرودگاه بین‌المللی زوارتنوتس', countryFa: 'ارمنستان', tz: 'Asia/Yerevan' },
  { code: 'LWN', cityFa: 'گیومری', airportNameFa: 'فرودگاه بین‌المللی شیراک', countryFa: 'ارمنستان', tz: 'Asia/Yerevan' },

  { code: 'BGW', cityFa: 'بغداد', airportNameFa: 'فرودگاه بین‌المللی بغداد', countryFa: 'عراق', tz: 'Asia/Baghdad' },
  { code: 'NJF', cityFa: 'نجف', airportNameFa: 'فرودگاه بین‌المللی نجف', countryFa: 'عراق', tz: 'Asia/Baghdad' },
  { code: 'EBL', cityFa: 'اربیل', airportNameFa: 'فرودگاه بین‌المللی اربیل', countryFa: 'عراق', tz: 'Asia/Baghdad' },
  { code: 'BSR', cityFa: 'بصره', airportNameFa: 'فرودگاه بین‌المللی بصره', countryFa: 'عراق', tz: 'Asia/Baghdad' },
  { code: 'ISU', cityFa: 'سلیمانیه', airportNameFa: 'فرودگاه بین‌المللی سلیمانیه', countryFa: 'عراق', tz: 'Asia/Baghdad' },
  { code: 'KIK', cityFa: 'کرکوک', airportNameFa: 'فرودگاه بین‌المللی کرکوک', countryFa: 'عراق', tz: 'Asia/Baghdad' },
] as const;

export const AIRPORT_REFERENCE_COUNTRIES = [
  'ایران',
  'امارات',
  'عمان',
  'قطر',
  'ترکیه',
  'ارمنستان',
  'عراق',
] as const;
